import type { Audio } from "@/lib/supabase/types";

export const AUDIOS_SEED: Audio[] = [
  {
    id: "a-oracao-01",
    tipo: "oracao",
    titulo: "Oração da manhã — 5 min",
    descricao: "Uma oração guiada para começar o dia em comunhão.",
    duracao_seg: 300,
    url: "",
    capa_url: null,
    publicado: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "a-oracao-02",
    tipo: "oracao",
    titulo: "Oração antes de dormir — 7 min",
    descricao: "Repouse o dia aos pés do Pai.",
    duracao_seg: 420,
    url: "",
    capa_url: null,
    publicado: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "a-oracao-03",
    tipo: "oracao",
    titulo: "Oração pela ansiedade — 10 min",
    descricao: "Silencie os pensamentos e descanse.",
    duracao_seg: 600,
    url: "",
    capa_url: null,
    publicado: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "a-devo-01",
    tipo: "devocional",
    titulo: "Salmo 23 narrado",
    descricao: "Meditação guiada sobre o Salmo 23.",
    duracao_seg: 360,
    url: "",
    capa_url: null,
    publicado: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "a-devo-02",
    tipo: "devocional",
    titulo: "Sermão do Monte — meditação",
    descricao: "Uma passagem por trás das bem-aventuranças.",
    duracao_seg: 900,
    url: "",
    capa_url: null,
    publicado: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "a-amb-01",
    tipo: "ambiente",
    titulo: "Chuva suave (30 min)",
    descricao: "Para orar, ler ou descansar.",
    duracao_seg: 1800,
    url: "",
    capa_url: null,
    publicado: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "a-amb-02",
    tipo: "ambiente",
    titulo: "Coral gregoriano (60 min)",
    descricao: "Ambiente contemplativo para silêncio e meditação.",
    duracao_seg: 3600,
    url: "",
    capa_url: null,
    publicado: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "a-amb-03",
    tipo: "ambiente",
    titulo: "Piano + natureza (45 min)",
    descricao: "Para focar no trabalho ou estudo com paz.",
    duracao_seg: 2700,
    url: "",
    capa_url: null,
    publicado: true,
    created_at: new Date().toISOString(),
  },
];
