import type { BibleBook } from "@/lib/supabase/types";

/**
 * Lista completa dos 66 livros da Bíblia (protestante) em PT-BR,
 * com abreviações usadas em apps brasileiros.
 */
export const BIBLE_BOOKS: Omit<BibleBook, "version_id">[] = [
  // AT (39)
  { id: 1, abbrev: "gn", nome: "Gênesis", testamento: "AT", ordem: 1, total_capitulos: 50 },
  { id: 2, abbrev: "ex", nome: "Êxodo", testamento: "AT", ordem: 2, total_capitulos: 40 },
  { id: 3, abbrev: "lv", nome: "Levítico", testamento: "AT", ordem: 3, total_capitulos: 27 },
  { id: 4, abbrev: "nm", nome: "Números", testamento: "AT", ordem: 4, total_capitulos: 36 },
  { id: 5, abbrev: "dt", nome: "Deuteronômio", testamento: "AT", ordem: 5, total_capitulos: 34 },
  { id: 6, abbrev: "js", nome: "Josué", testamento: "AT", ordem: 6, total_capitulos: 24 },
  { id: 7, abbrev: "jz", nome: "Juízes", testamento: "AT", ordem: 7, total_capitulos: 21 },
  { id: 8, abbrev: "rt", nome: "Rute", testamento: "AT", ordem: 8, total_capitulos: 4 },
  { id: 9, abbrev: "1sm", nome: "1 Samuel", testamento: "AT", ordem: 9, total_capitulos: 31 },
  { id: 10, abbrev: "2sm", nome: "2 Samuel", testamento: "AT", ordem: 10, total_capitulos: 24 },
  { id: 11, abbrev: "1rs", nome: "1 Reis", testamento: "AT", ordem: 11, total_capitulos: 22 },
  { id: 12, abbrev: "2rs", nome: "2 Reis", testamento: "AT", ordem: 12, total_capitulos: 25 },
  { id: 13, abbrev: "1cr", nome: "1 Crônicas", testamento: "AT", ordem: 13, total_capitulos: 29 },
  { id: 14, abbrev: "2cr", nome: "2 Crônicas", testamento: "AT", ordem: 14, total_capitulos: 36 },
  { id: 15, abbrev: "ed", nome: "Esdras", testamento: "AT", ordem: 15, total_capitulos: 10 },
  { id: 16, abbrev: "ne", nome: "Neemias", testamento: "AT", ordem: 16, total_capitulos: 13 },
  { id: 17, abbrev: "et", nome: "Ester", testamento: "AT", ordem: 17, total_capitulos: 10 },
  { id: 18, abbrev: "jó", nome: "Jó", testamento: "AT", ordem: 18, total_capitulos: 42 },
  { id: 19, abbrev: "sl", nome: "Salmos", testamento: "AT", ordem: 19, total_capitulos: 150 },
  { id: 20, abbrev: "pv", nome: "Provérbios", testamento: "AT", ordem: 20, total_capitulos: 31 },
  { id: 21, abbrev: "ec", nome: "Eclesiastes", testamento: "AT", ordem: 21, total_capitulos: 12 },
  { id: 22, abbrev: "ct", nome: "Cânticos", testamento: "AT", ordem: 22, total_capitulos: 8 },
  { id: 23, abbrev: "is", nome: "Isaías", testamento: "AT", ordem: 23, total_capitulos: 66 },
  { id: 24, abbrev: "jr", nome: "Jeremias", testamento: "AT", ordem: 24, total_capitulos: 52 },
  { id: 25, abbrev: "lm", nome: "Lamentações", testamento: "AT", ordem: 25, total_capitulos: 5 },
  { id: 26, abbrev: "ez", nome: "Ezequiel", testamento: "AT", ordem: 26, total_capitulos: 48 },
  { id: 27, abbrev: "dn", nome: "Daniel", testamento: "AT", ordem: 27, total_capitulos: 12 },
  { id: 28, abbrev: "os", nome: "Oséias", testamento: "AT", ordem: 28, total_capitulos: 14 },
  { id: 29, abbrev: "jl", nome: "Joel", testamento: "AT", ordem: 29, total_capitulos: 3 },
  { id: 30, abbrev: "am", nome: "Amós", testamento: "AT", ordem: 30, total_capitulos: 9 },
  { id: 31, abbrev: "ob", nome: "Obadias", testamento: "AT", ordem: 31, total_capitulos: 1 },
  { id: 32, abbrev: "jn", nome: "Jonas", testamento: "AT", ordem: 32, total_capitulos: 4 },
  { id: 33, abbrev: "mq", nome: "Miquéias", testamento: "AT", ordem: 33, total_capitulos: 7 },
  { id: 34, abbrev: "na", nome: "Naum", testamento: "AT", ordem: 34, total_capitulos: 3 },
  { id: 35, abbrev: "hc", nome: "Habacuque", testamento: "AT", ordem: 35, total_capitulos: 3 },
  { id: 36, abbrev: "sf", nome: "Sofonias", testamento: "AT", ordem: 36, total_capitulos: 3 },
  { id: 37, abbrev: "ag", nome: "Ageu", testamento: "AT", ordem: 37, total_capitulos: 2 },
  { id: 38, abbrev: "zc", nome: "Zacarias", testamento: "AT", ordem: 38, total_capitulos: 14 },
  { id: 39, abbrev: "ml", nome: "Malaquias", testamento: "AT", ordem: 39, total_capitulos: 4 },
  // NT (27)
  { id: 40, abbrev: "mt", nome: "Mateus", testamento: "NT", ordem: 40, total_capitulos: 28 },
  { id: 41, abbrev: "mc", nome: "Marcos", testamento: "NT", ordem: 41, total_capitulos: 16 },
  { id: 42, abbrev: "lc", nome: "Lucas", testamento: "NT", ordem: 42, total_capitulos: 24 },
  { id: 43, abbrev: "jo", nome: "João", testamento: "NT", ordem: 43, total_capitulos: 21 },
  { id: 44, abbrev: "at", nome: "Atos", testamento: "NT", ordem: 44, total_capitulos: 28 },
  { id: 45, abbrev: "rm", nome: "Romanos", testamento: "NT", ordem: 45, total_capitulos: 16 },
  { id: 46, abbrev: "1co", nome: "1 Coríntios", testamento: "NT", ordem: 46, total_capitulos: 16 },
  { id: 47, abbrev: "2co", nome: "2 Coríntios", testamento: "NT", ordem: 47, total_capitulos: 13 },
  { id: 48, abbrev: "gl", nome: "Gálatas", testamento: "NT", ordem: 48, total_capitulos: 6 },
  { id: 49, abbrev: "ef", nome: "Efésios", testamento: "NT", ordem: 49, total_capitulos: 6 },
  { id: 50, abbrev: "fp", nome: "Filipenses", testamento: "NT", ordem: 50, total_capitulos: 4 },
  { id: 51, abbrev: "cl", nome: "Colossenses", testamento: "NT", ordem: 51, total_capitulos: 4 },
  { id: 52, abbrev: "1ts", nome: "1 Tessalonicenses", testamento: "NT", ordem: 52, total_capitulos: 5 },
  { id: 53, abbrev: "2ts", nome: "2 Tessalonicenses", testamento: "NT", ordem: 53, total_capitulos: 3 },
  { id: 54, abbrev: "1tm", nome: "1 Timóteo", testamento: "NT", ordem: 54, total_capitulos: 6 },
  { id: 55, abbrev: "2tm", nome: "2 Timóteo", testamento: "NT", ordem: 55, total_capitulos: 4 },
  { id: 56, abbrev: "tt", nome: "Tito", testamento: "NT", ordem: 56, total_capitulos: 3 },
  { id: 57, abbrev: "fm", nome: "Filemom", testamento: "NT", ordem: 57, total_capitulos: 1 },
  { id: 58, abbrev: "hb", nome: "Hebreus", testamento: "NT", ordem: 58, total_capitulos: 13 },
  { id: 59, abbrev: "tg", nome: "Tiago", testamento: "NT", ordem: 59, total_capitulos: 5 },
  { id: 60, abbrev: "1pe", nome: "1 Pedro", testamento: "NT", ordem: 60, total_capitulos: 5 },
  { id: 61, abbrev: "2pe", nome: "2 Pedro", testamento: "NT", ordem: 61, total_capitulos: 3 },
  { id: 62, abbrev: "1jo", nome: "1 João", testamento: "NT", ordem: 62, total_capitulos: 5 },
  { id: 63, abbrev: "2jo", nome: "2 João", testamento: "NT", ordem: 63, total_capitulos: 1 },
  { id: 64, abbrev: "3jo", nome: "3 João", testamento: "NT", ordem: 64, total_capitulos: 1 },
  { id: 65, abbrev: "jd", nome: "Judas", testamento: "NT", ordem: 65, total_capitulos: 1 },
  { id: 66, abbrev: "ap", nome: "Apocalipse", testamento: "NT", ordem: 66, total_capitulos: 22 },
];

export function findBookByAbbrev(abbrev: string) {
  return BIBLE_BOOKS.find((b) => b.abbrev === abbrev.toLowerCase());
}
