import type { Igreja } from "@/lib/supabase/types";

export const IGREJAS_SEED: Igreja[] = [
  {
    id: "ig-001",
    nome: "Lagoinha Alphaville",
    denominacao: "Batista",
    endereco: "Alameda Rio Negro, 585 — Alphaville",
    cidade: "Barueri",
    estado: "SP",
    cep: "06454-000",
    telefone: null,
    email: null,
    website: "https://www.lagoinhaalpha.com.br",
    lat: -23.4979,
    lng: -46.85,
    horarios: { "quarta": "20:00", "domingo": "10:00" },
    created_at: new Date().toISOString(),
  },
  {
    id: "ig-002",
    nome: "Videira Central",
    denominacao: "Não denominacional",
    endereco: "Av. das Nações Unidas, 12901 — Brooklin",
    cidade: "São Paulo",
    estado: "SP",
    cep: "04578-000",
    telefone: null,
    email: null,
    website: null,
    lat: -23.617,
    lng: -46.698,
    horarios: { "domingo": "10:00, 17:00, 19:30" },
    created_at: new Date().toISOString(),
  },
  {
    id: "ig-003",
    nome: "Bola de Neve",
    denominacao: "Não denominacional",
    endereco: "Rua Treze de Maio, 560 — Bela Vista",
    cidade: "São Paulo",
    estado: "SP",
    cep: "01327-000",
    telefone: null,
    email: null,
    website: null,
    lat: -23.556,
    lng: -46.646,
    horarios: { "terça": "20:00", "domingo": "18:00" },
    created_at: new Date().toISOString(),
  },
];
