import type { QuizPergunta } from "@/lib/supabase/types";

export const QUIZ_SEED: QuizPergunta[] = [
  {
    id: "q-001",
    pergunta: "Quantos livros há na Bíblia (AT + NT)?",
    alternativas: [
      { id: "a", texto: "66" },
      { id: "b", texto: "72" },
      { id: "c", texto: "39" },
      { id: "d", texto: "27" },
    ],
    correta: "a",
    explicacao: "39 no Antigo + 27 no Novo = 66 livros.",
    categoria: "Geral",
    nivel: 1,
    publicado: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "q-002",
    pergunta: "Qual é o primeiro livro da Bíblia?",
    alternativas: [
      { id: "a", texto: "Êxodo" },
      { id: "b", texto: "Gênesis" },
      { id: "c", texto: "Salmos" },
      { id: "d", texto: "Mateus" },
    ],
    correta: "b",
    explicacao: "Gênesis abre a Bíblia narrando a criação.",
    categoria: "AT",
    nivel: 1,
    publicado: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "q-003",
    pergunta: "Quem construiu a arca?",
    alternativas: [
      { id: "a", texto: "Moisés" },
      { id: "b", texto: "Abraão" },
      { id: "c", texto: "Noé" },
      { id: "d", texto: "Davi" },
    ],
    correta: "c",
    explicacao: "Noé obedeceu Deus e construiu a arca (Gn 6).",
    categoria: "AT",
    nivel: 1,
    publicado: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "q-004",
    pergunta: "Quem escreveu a maioria dos Salmos?",
    alternativas: [
      { id: "a", texto: "Salomão" },
      { id: "b", texto: "Moisés" },
      { id: "c", texto: "Davi" },
      { id: "d", texto: "Samuel" },
    ],
    correta: "c",
    explicacao: "O rei Davi escreveu 73 dos 150 salmos.",
    categoria: "AT",
    nivel: 2,
    publicado: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "q-005",
    pergunta: "Quantos discípulos Jesus escolheu?",
    alternativas: [
      { id: "a", texto: "10" },
      { id: "b", texto: "12" },
      { id: "c", texto: "7" },
      { id: "d", texto: "24" },
    ],
    correta: "b",
    explicacao: "Os 12 apóstolos foram escolhidos por Jesus.",
    categoria: "NT",
    nivel: 1,
    publicado: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "q-006",
    pergunta: "Qual cidade Jesus nasceu?",
    alternativas: [
      { id: "a", texto: "Nazaré" },
      { id: "b", texto: "Jerusalém" },
      { id: "c", texto: "Belém" },
      { id: "d", texto: "Cafarnaum" },
    ],
    correta: "c",
    explicacao: "Jesus nasceu em Belém, conforme profetizado em Miqueias 5:2.",
    categoria: "NT",
    nivel: 1,
    publicado: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "q-007",
    pergunta: "O que aconteceu no Pentecostes?",
    alternativas: [
      { id: "a", texto: "Jesus ressuscitou" },
      { id: "b", texto: "Veio o Espírito Santo sobre os discípulos" },
      { id: "c", texto: "Paulo se converteu" },
      { id: "d", texto: "Jesus foi batizado" },
    ],
    correta: "b",
    explicacao: "Em Atos 2, o Espírito Santo desce sobre os discípulos.",
    categoria: "NT",
    nivel: 2,
    publicado: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "q-008",
    pergunta: "Quem enfrentou Golias?",
    alternativas: [
      { id: "a", texto: "Saul" },
      { id: "b", texto: "Davi" },
      { id: "c", texto: "Sansão" },
      { id: "d", texto: "Gideão" },
    ],
    correta: "b",
    explicacao: "Davi, ainda jovem, venceu Golias com uma funda (1 Sm 17).",
    categoria: "AT",
    nivel: 1,
    publicado: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "q-009",
    pergunta: "Qual o primeiro mandamento da lei segundo Jesus?",
    alternativas: [
      { id: "a", texto: "Não matarás" },
      { id: "b", texto: "Amarás o Senhor teu Deus de todo o teu coração" },
      { id: "c", texto: "Honrarás pai e mãe" },
      { id: "d", texto: "Amarás o próximo" },
    ],
    correta: "b",
    explicacao: "Jesus cita Dt 6:5 em Mateus 22:37.",
    categoria: "NT",
    nivel: 2,
    publicado: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "q-010",
    pergunta: "Quantos livros tem o Novo Testamento?",
    alternativas: [
      { id: "a", texto: "27" },
      { id: "b", texto: "39" },
      { id: "c", texto: "12" },
      { id: "d", texto: "21" },
    ],
    correta: "a",
    explicacao: "O NT tem 27 livros.",
    categoria: "Geral",
    nivel: 1,
    publicado: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "q-011",
    pergunta: "Quem foi o primeiro mártir cristão?",
    alternativas: [
      { id: "a", texto: "Pedro" },
      { id: "b", texto: "Estêvão" },
      { id: "c", texto: "Tiago" },
      { id: "d", texto: "Paulo" },
    ],
    correta: "b",
    explicacao: "Estêvão foi apedrejado em Atos 7.",
    categoria: "NT",
    nivel: 3,
    publicado: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "q-012",
    pergunta: "O que significa 'evangelho'?",
    alternativas: [
      { id: "a", texto: "Ensinamento" },
      { id: "b", texto: "Boa nova / boa notícia" },
      { id: "c", texto: "Revelação" },
      { id: "d", texto: "Palavra de Deus" },
    ],
    correta: "b",
    explicacao:
      "Do grego euangélion: boa nova. Refere-se à mensagem de salvação em Cristo.",
    categoria: "Geral",
    nivel: 2,
    publicado: true,
    created_at: new Date().toISOString(),
  },
];

export function quizSortido(n = 5): QuizPergunta[] {
  return [...QUIZ_SEED].sort(() => Math.random() - 0.5).slice(0, n);
}
